import ChatPanel from '../components/ChatPanel'

export default function ChatPage() {
  return (
    <div className="space-y-6">
      <section className="glass-panel p-6">
        <p className="text-sm uppercase tracking-[0.3em] text-cyan-300/70">AI Chat</p>
        <h1 className="mt-3 text-3xl font-semibold">GridMind conversational assistant</h1>
        <p className="mt-3 max-w-3xl text-white/60">
          Ask about savings, battery strategy, weather effects, or the current report. Replies are generated by the backend chat endpoint with the latest analysis context.
        </p>
      </section>

      <div className="min-h-[640px]">
        <ChatPanel />
      </div>
    </div>
  )
}